default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost

development: #開発環境
  <<: *default
  database: myapp_development
  # host: db
  username: postgres
  password: password

test: #テスト環境
  <<: *default
  database: myapp_test
  # host: db
  username: postgres
  password: password

production: #本番環境
  <<: *default
  database: myapp_production
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
